name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --file ./docker/Dockerfile . --tag quyc07/axum-web:latest
      - name: Push the Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push quyc07/axum-web:latest
      - name: Build the school-server Docker image
        run: docker build --file ./docker/school-server/Dockerfile . --tag quyc07/school-server:latest
      - name: Push the school-server Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push quyc07/school-server:latest
