name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Protocol Buffers
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose